# Site settings

title: JonMarkSearle # Title of your site
email: JonMarkSearle@gmail.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Principles for Life
- Learn - Discover, Share, Master
- Love - Build Relationships, Express Joy
- Leave a Legacy - Invent, Improve and Help

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonmarksearle.com" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     jonmarksearle  # Replace this with your Twitter username
github_username:      jonmarksearle  # Replace this with your GitHub username
linkedin_username:    jonmarksearle  # Replace this with your LinkedIn username
google_plus_username: jonmarksearle  # Replace this with your Google+ username
facebook_username:    jonmarksearle  # Replace this with your Facebook username

# Build settings
markdown: kramdown
